import re
from typing import List, Optional, Union, Dict, Any
from pydantic import BaseModel, Field, field_validator

def _validate_strict_string(
    field_name: str,
    value: Any,
    min_len: int,
    max_len: int,
    required: bool = True,
    require_meaningful: bool = True
) -> str:
    if value is None:
        if required:
            raise ValueError(f"'{field_name}' is required and cannot be null.")
        return ""
    if isinstance(value, bool):
        raise ValueError(f"'{field_name}' must be a string, received boolean.")
    if not isinstance(value, str):
        raise ValueError(f"'{field_name}' must be a string, received {type(value).__name__}.")
    stripped = value.strip()
    if required and len(stripped) == 0:
        raise ValueError(f"'{field_name}' cannot be empty or contain only whitespace.")
    if required and len(stripped) < min_len:
        raise ValueError(f"'{field_name}' must be at least {min_len} characters (currently {len(stripped)}).")
    if len(stripped) > max_len:
        raise ValueError(f"'{field_name}' exceeds maximum allowed length of {max_len} characters (currently {len(stripped)}).")

    if require_meaningful and stripped:
        letters = re.findall(r'[a-zA-Z]', stripped)
        if len(letters) < 2:
            raise ValueError(f"'{field_name}' must contain meaningful text with letters, not purely numbers or symbols.")
        if re.search(r'(.)\1{4,}', stripped):
            raise ValueError(f"'{field_name}' contains excessive repetitive characters and appears invalid.")
        alnum = [c.lower() for c in stripped if c.isalnum()]
        if len(alnum) >= 6 and len(set(alnum)) < 3:
            raise ValueError(f"'{field_name}' lacks sufficient character variety and appears to be meaningless spam.")

    return stripped

class DatabaseInput(BaseModel):
    """Input payload for Agent 2 (Database Agent)."""
    project_name: str = Field(default="", description="Project or task name (2-120 chars)")
    description: str = Field(default="", description="Project description (5-5000 chars)")
    requirements: Union[List[str], str] = Field(default="", description="Requirements list or string")
    additional_info: Optional[str] = Field(default="", description="Additional context or constraints")
    markdown_path: Optional[str] = Field(default="", description="Path of markdown generated by Agent 1")
    workflow_run_id: Optional[str] = Field(default=None, description="Workflow run ID for audit tracking")

    @field_validator("project_name", mode="before")
    @classmethod
    def validate_name(cls, v: Any) -> str:
        if v == "" or v is None:
            return ""
        return _validate_strict_string("project_name", v, min_len=2, max_len=120, required=False, require_meaningful=True)

    @field_validator("description", mode="before")
    @classmethod
    def validate_desc(cls, v: Any) -> str:
        if v == "" or v is None:
            return ""
        return _validate_strict_string("description", v, min_len=5, max_len=5000, required=False, require_meaningful=True)

    @field_validator("requirements", mode="before")
    @classmethod
    def validate_reqs(cls, v: Any) -> str:
        if v == "" or v is None:
            return ""
        if isinstance(v, bool):
            raise ValueError("'requirements' must be a string, received boolean.")
        if isinstance(v, (int, float, dict)):
            raise ValueError(f"'requirements' must be a string, received {type(v).__name__}.")
        if isinstance(v, list):
            if len(v) == 0:
                raise ValueError("'requirements' list cannot be empty.")
            cleaned = []
            for idx, item in enumerate(v):
                if not isinstance(item, str) or isinstance(item, bool):
                    raise ValueError(f"Requirement item at index {idx} must be a string, received {type(item).__name__}.")
                item_str = item.strip()
                if item_str:
                    _validate_strict_string(f"Requirement item at index {idx}", item_str, min_len=2, max_len=1000, required=True, require_meaningful=True)
                    cleaned.append(item_str)
            if not cleaned:
                raise ValueError("'requirements' cannot be empty or contain only whitespace.")
            return "\n".join(cleaned)
        return _validate_strict_string("requirements", v, min_len=5, max_len=5000, required=True, require_meaningful=True)

    @field_validator("additional_info", mode="before")
    @classmethod
    def validate_info(cls, v: Any) -> str:
        if v is None:
            return ""
        if isinstance(v, bool):
            raise ValueError("'additional_info' must be a string if provided, received boolean.")
        if not isinstance(v, str):
            raise ValueError(f"'additional_info' must be a string if provided, received {type(v).__name__}.")
        stripped = v.strip()
        if len(stripped) > 3000:
            raise ValueError(f"'additional_info' exceeds maximum length of 3000 characters (currently {len(stripped)}).")
        if stripped:
            if re.search(r'(.)\1{4,}', stripped):
                raise ValueError("'additional_info' contains excessive repetitive characters and appears invalid.")
            if len(stripped) >= 5 and len(re.findall(r'[a-zA-Z]', stripped)) < 2:
                raise ValueError("'additional_info' must contain meaningful text if provided.")
        return stripped

class DatabaseOutput(BaseModel):
    """
    Output payload returned by Agent 2 (Database Agent).
    Conforms to required specification:
    {
      "status": "success/failure",
      "record_id": "...",
      "message": "..."
    }
    """
    status: str = Field(..., description="'success' or 'failure'")
    record_id: Optional[Union[int, str]] = Field(default=None, description="Primary key record ID in database")
    message: str = Field(..., description="Human-readable message of the operation outcome")
    action: str = Field(default="inserted", description="'inserted', 'updated', or 'none'")
    project_name: Optional[str] = Field(default="", description="Project name")
    slug: Optional[str] = Field(default="", description="Unique slug for the project")
    version: int = Field(default=1, description="Record revision version")
    operation: Optional[str] = Field(default="", description="Technical description of database action")
    table: str = Field(default="projects", description="Database table name")
    airtable_record_id: Optional[str] = Field(default=None, description="Corresponding record ID in Airtable")
    success: bool = Field(default=True, description="Whether the DB operation succeeded")
    error: Optional[str] = Field(default=None, description="Error message if failed")
    timestamp: str = Field(default="", description="Timestamp of database operation")

    def to_dict(self) -> Dict[str, Any]:
        """Return the exact primary dictionary requested by user specification."""
        return {
            "status": self.status,
            "record_id": str(self.record_id) if self.record_id is not None else "",
            "message": self.message
        }
