-- Database Schema for Multi-Agent Workflow System
-- Engine: SQLite 3

-- Projects Table: Stores main task/project information submitted through Entry Form
CREATE TABLE IF NOT EXISTS projects (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    project_name TEXT NOT NULL UNIQUE COLLATE NOCASE,
    slug TEXT NOT NULL UNIQUE,
    description TEXT NOT NULL,
    requirements TEXT NOT NULL,           -- JSON array of requirements
    additional_info TEXT,                 -- Optional additional context
    markdown_path TEXT,                   -- Path to markdown file generated by Agent 1
    version INTEGER DEFAULT 1,            -- Version counter for updates
    status TEXT DEFAULT 'active',         -- Status: 'active', 'archived', 'completed'
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Index for fast lookup by slug and project name
CREATE INDEX IF NOT EXISTS idx_projects_slug ON projects(slug);
CREATE INDEX IF NOT EXISTS idx_projects_name ON projects(project_name);

-- Workflow Runs Table: Stores audit logs of every agent execution
CREATE TABLE IF NOT EXISTS workflow_runs (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    workflow_run_id TEXT NOT NULL,
    project_id INTEGER,
    project_name TEXT NOT NULL,
    agent_name TEXT NOT NULL,             -- 'agent1_markdown', 'agent2_database', 'agent3_documentation'
    action TEXT NOT NULL,                 -- e.g., 'created', 'updated', 'inserted', 'generated'
    status TEXT NOT NULL,                 -- 'success', 'warning', 'error'
    details TEXT,                         -- JSON payload with execution details
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE
);

-- Index for workflow run tracing
CREATE INDEX IF NOT EXISTS idx_workflow_runs_run_id ON workflow_runs(workflow_run_id);
CREATE INDEX IF NOT EXISTS idx_workflow_runs_project_id ON workflow_runs(project_id);
